name: VitalHome
version: @version@
main: com.tamrielnetwork.vitalhome.VitalHome
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to set homes and teleport to them.
commands:
  vitalhome:
    description: "Main command"
    usage: "/vitalhome"
permissions:
  vitalhome.home:
    description: "Permission to teleport home"
    default: op
  vitalhome.sethome:
    description: "Permission to set a home"
    default: op
  vitalhome.homes:
    description: "Permission with number of homes a player can set (fex. vitalhome.homes.2 = 2 homes)"
    default: op